name: Scheduled crawler and deployment

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        pip install lxml        
        pip install bs4
        pip install requests
    - name: run Scraping
      run: |
        cd scrap
        python Scraping.py
    - name: commit
      run: |
        git config --global user.email yanxia_he@126.com
        git config --global user.name Yanxiall
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: npm install, build
      run: |
        cd covid19map
        npm install
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: covid19map/dist
