name: Python application

on:
  push:
  schedule:
    - cron: '2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        pip install lxml        
        pip install bs4
        pip install requests
    - name: run Scraping
      run: |
        cd scrap
        python Scraping.py
    - name: commit
      run: |
        git config --global user.email yanxia_he@126.com
        git config --global user.name Yanxiall
        git add .
        git commit -m "update" -a
        git remote set-url origin https://Yanxiall:${{secrets.GITHUB_TOKEN}}@github.com/Yanxiall/Covid-19Germany.git
        git remote -v
        git checkout -b gh-pages
        git push origin HEAD:gh-pages --force
    - name: npm install, build
      run: |
        cd covid19map
        npm install
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: myPages
        PUBLISH_DIR: covid19map/dist
